### ISSUE TITLE
Issue with support The MWB zendesk woo order sync "accept" button  

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/MWB-Zendesk-Woo-Order-Sync#1]
When we accept "support The MWB zendesk woo order sync.." from one tab and on other tab same same page is open and again we try to accept this again then it is again send the email rather than notify that email is already sent.
![zendesk](https://user-images.githubusercontent.com/48902379/65424169-7ab12a80-de28-11e9-8dda-9803be9a1663.png)

**Comment by ced-deepali** [comment]
fixed
