### ISSUE TITLE
issue with the drag and drop of the fields

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/mwb-zendesk-woo-order-sync#12]
os: window 11
wp: 5.8.2
wc: 5.9.0
version: 2.0.3
path: order configuration
description: drag and drop feature in order configuration is not working properly.
https://www.loom.com/share/9f16b6d921fd497aa29bb653967dafe1

**Comment by shubhankar-cedcoss** [comment]
its workign fine

**Comment by prateek-cedcoss** [comment]
okay
