### ISSUE TITLE
issue with the organization name

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/mwb-zendesk-woo-order-sync#13]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.3
description: when we fill the organization details in the form, it does not get fetch to the zendesk.

**Comment by shubhankar-cedcoss** [comment]
will release this feature in next update, for now I am removing this code

**Comment by prateek-cedcoss** [comment]
okay
