### ISSUE TITLE
no validation in phone number field

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/mwb-zendesk-woo-order-sync#14]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.3
description: phone number field accept character also.
![image](https://user-images.githubusercontent.com/86113814/144562146-2172d955-00e4-49c3-b8e6-ff0d17a0b79a.png)

**Comment by shubhankar-cedcoss** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
fix
