### ISSUE TITLE
issue with the account setting page and order confrigration page in responsive

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/mwb-zendesk-woo-order-sync#16]
https://www.loom.com/share/a4862db9991f467290582921ed108f12

form page:
![image](https://user-images.githubusercontent.com/86113814/144575759-032bbcc1-2b9d-4ad6-bcd6-f2ba2f55b06f.png)

**Comment by anmolui** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/79319224/145403855-4ba73256-00ff-4d3b-89d7-501bc672e69c.png)

**Comment by prateek-cedcoss** [comment]
issue with add comment in ticket history is not appropriate.
![image](https://user-images.githubusercontent.com/86113814/147459387-9131d686-4310-4133-8530-17e76c16a1c0.png)

**Comment by prateek-cedcoss** [comment]
not required fir the responsive mode
