### ISSUE TITLE
getting php notice in account setting page

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/mwb-zendesk-woo-order-sync#3]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.3
path: zendesk account setting 
description: when we click on save button after filling the required fields, then php notice occurs.
![setting php notice](https://user-images.githubusercontent.com/86113814/144223397-aa02c07a-b0aa-4313-a329-e4bd0bebe79b.png)

**Comment by shubhankar-cedcoss** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
fix
