### ISSUE TITLE
not able to see hidden text

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/mwb-zendesk-woo-order-sync#5]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.3
path: zendesk account setting 
description: in Zendesk API Token of setting no unhide option to see the information.
![hidden](https://user-images.githubusercontent.com/86113814/144234039-14ea7024-477b-4ede-b21b-aa22f1363170.png)

**Comment by shubhankar-cedcoss** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
implemented
