### ISSUE TITLE
no  content information about the box in Order Configuration setting page

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/mwb-zendesk-woo-order-sync#6]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.3
path: Order Configuration setting
description: no heading for the box. it make difficult to determine which box is for add the fields or which for remove.
![content issue](https://user-images.githubusercontent.com/86113814/144234908-32431ea0-7567-4bff-a3d4-f9ea5aaae664.png)

**Comment by shubhankar-cedcoss** [comment]
done
