### ISSUE TITLE
setting , document and support button are missing

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/mwb-zendesk-woo-order-sync#7]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.3
path: installed plugins
description: no support document and setting button 
![image](https://user-images.githubusercontent.com/86113814/144235638-2a1f843c-f970-44f1-a548-308fb36696e0.png)

**Comment by shubhankar-cedcoss** [comment]
done

**Comment by prateek-cedcoss** [comment]
fix
